-- SQLite

CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL UNIQUE,
    Password_hash TEXT NOT NULL,
    Salt TEXT NOT NULL,
    First_name TEXT NOT NULL,
    Last_name TEXT NOT NULL,
    Role TEXT NOT NULL DEFAULT 'customer',
    Status INTEGER NOT NULL DEFAULT 0,
    Phone_number TEXT,
    Created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE IF NOT EXISTS Customers(
    CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    Address TEXT
);

CREATE TABLE IF NOT EXISTS Merchants(
    MerchantID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    MerchantName TEXT NOT NULL,
    MerchantAddress TEXT,
    Verified BOOLEAN NOT NULL DEFAULT FALSE,
    StoreScore REAL NOT NULL DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS MerchantDocuments (
    ImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    MerchantID INTEGER NOT NULL REFERENCES Merchants(MerchantID) ON DELETE CASCADE,
    imgPath TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Orders(
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerID INTEGER REFERENCES Customers(CustomerID) ON DELETE SET NULL,
    MerchantID INTEGER REFERENCES Merchants(MerchantID) ON DELETE SET NULL,
    OrderStatus TEXT NOT NULL CHECK (OrderStatus IN ('Pending', 'Accepted', 'Ready For Pickup', 'Completed', 'Cancelled')) DEFAULT 'Pending',
    TimeOrdered TEXT NOT NULL,
    TimeCompleted TEXT,
    TotalAmount REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderItems(
    OrderItemID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderID INTEGER NOT NULL REFERENCES Orders(OrderID) ON DELETE CASCADE,
    ItemID INTEGER REFERENCES MenuItems(ItemID) ON DELETE SET NULL,
    Quantity INTEGER NOT NULL,
    PriceAtPurchase REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS MenuItems(
    ItemID INTEGER PRIMARY KEY AUTOINCREMENT,
    MerchantID INTEGER NOT NULL REFERENCES Merchants(MerchantID) ON DELETE CASCADE,
    ItemName TEXT NOT NULL,
    Calories INTEGER NOT NULL CHECK (Calories >= 0),
    Price REAL NOT NULL,
    Description TEXT NOT NULL,
    Recipe TEXT
);

CREATE TABLE IF NOT EXISTS Reviews(
    ReviewID INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerID INTEGER NOT NULL REFERENCES Customers(CustomerID),
    MerchantID INTEGER NOT NULL REFERENCES Merchants(MerchantID),
    Rating INTEGER NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
    Comment TEXT,
    ReviewDate TEXT NOT NULL,
    Anonymous BOOLEAN NOT NULL DEFAULT FALSE
);

